spring:
  rabbitmq:
    host: 192.168.68.128
    username: admin
    password: admin
    virtual-host: /
    port: 5672
    listener:
      simple:
#        消费者最小数量
        concurrency: 10
#        消费者最大数量
        max-concurrency: 10
#        限制消费者每次只处理一条消息,处理完再处理下一条消息
        prefetch: 1
#        启动时是否默认启动容器
        auto-startup: true
#        被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
#        发布重试,默认false
        enabled: true
        #        重试时间 默认1000ms
        initial-interval: 1000
#        最大尝试次数3
        max-attempts: 3
#        重试最大间隔时间,默认10000ms
        max-interval: 10000
#        重试间隔乘数
        multiplier: 1.0


  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
  resources:
#    启动默认静态资源处理，默认启动
    add-mappings: true
    cache:
      cachecontrol:
#        缓存相应的时间,默认启动
        max-age: 3600
    chain:
#      资源链启动缓存,默认启动
      cache: true
#      启用资源链
      enabled: true
#      启用h5应用缓存
      compressed: true
      html-application-cache: true
    static-locations: classpath:/static/
  #    关闭缓存
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: lihaotian..
    hikari:
#      连接池名
      pool-name: DateHikariCP
#      最小空闲链接数
      minimum-idle: 5
#      空闲链接存活最大时间
      idle-timeout: 1800000
#      最大连接数，默认10
      maximum-pool-size: 10
#      从连接池返回的链接自动提交
      auto-commit: true
#      链接最大存活时间
      max-lifetime: 1800000
      #      链接超时时间
      connection-timeout: 30000
#      测试链接是否可用的查询语句
      connection-test-query: SELECT 1
  redis:
    host: 192.168.68.128
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        #        最大连接数，默认8
        max-active: 8
        #        最大链接阻塞等待时间，默认-1
        max-wait: 10000ms
        #        最大空闲连接
        max-idle: 200
        min-idle: 5
mybatis-plus:
#   配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
#   配置Mybatis数据返回类型别名
  type-aliases-package: com.xxxx.seckill.pojo

logging:
  level:
    com.xxxx.seckill.mapper: debug
server:
  port: 8088
